# Configuration for the Data Preparation Operator (Step 0)
DATA_PREP:
  DATASET_REPO_ID: "TommyChien/UltraDomain"  # Hugging Face dataset repository ID
  DOWNLOAD_DIR: "../data/UltraDomain_download"  # Relative path to download the raw dataset
  OUTPUT_DIR: "../data/unique_contexts"      # Relative path to save the extracted unique context JSON files
  SKIP_DOWNLOAD: false                      # Set to true to skip download if data exists
  # MAX_RETRIES: 3                          # Optional: Add download retries
  # RETRY_DELAY: 5                          # Optional: Delay between retries (seconds)